
package AdminFrame;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.DriverManager;

import LoginFrames.Log_in_Frame;

public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeliveriesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDeleteTrucks = new javax.swing.JButton();
        btnViewDeliveries = new javax.swing.JButton();
        btnViewTrucks = new javax.swing.JButton();
        btnAddTrucks = new javax.swing.JButton();
        btnCompleteDeliveries = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPendingDriver = new javax.swing.JButton();
        btnOutForDelivery = new javax.swing.JButton();
        btnCompleted = new javax.swing.JButton();
        btnViewDrivers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true), "Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(153, 153, 153))); // NOI18N

        DeliveriesTable.setBackground(new java.awt.Color(153, 153, 153));
        DeliveriesTable.setForeground(new java.awt.Color(255, 255, 255));
        DeliveriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Truck ID", "Pick Up", "Drop Off", "Status", "Customer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DeliveriesTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        DeliveriesTable.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(DeliveriesTable);
        if (DeliveriesTable.getColumnModel().getColumnCount() > 0) {
            DeliveriesTable.getColumnModel().getColumn(0).setResizable(false);
            DeliveriesTable.getColumnModel().getColumn(1).setResizable(false);
            DeliveriesTable.getColumnModel().getColumn(2).setResizable(false);
            DeliveriesTable.getColumnModel().getColumn(3).setResizable(false);
            DeliveriesTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trucking And Delivery System");

        btnDeleteTrucks.setBackground(new java.awt.Color(153, 153, 153));
        btnDeleteTrucks.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteTrucks.setText("Delete Trucks");
        btnDeleteTrucks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeleteTrucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTrucksActionPerformed(evt);
            }
        });

        btnViewDeliveries.setBackground(new java.awt.Color(153, 153, 153));
        btnViewDeliveries.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDeliveries.setText("View Deliveries");
        btnViewDeliveries.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDeliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeliveriesActionPerformed(evt);
            }
        });

        btnViewTrucks.setBackground(new java.awt.Color(153, 153, 153));
        btnViewTrucks.setForeground(new java.awt.Color(255, 255, 255));
        btnViewTrucks.setText("View Trucks");
        btnViewTrucks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewTrucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTrucksActionPerformed(evt);
            }
        });

        btnAddTrucks.setBackground(new java.awt.Color(153, 153, 153));
        btnAddTrucks.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTrucks.setText("Add Trucks");
        btnAddTrucks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddTrucks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTrucksActionPerformed(evt);
            }
        });

        btnCompleteDeliveries.setBackground(new java.awt.Color(153, 153, 153));
        btnCompleteDeliveries.setForeground(new java.awt.Color(255, 255, 255));
        btnCompleteDeliveries.setText("Complete Deliveries");
        btnCompleteDeliveries.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCompleteDeliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteDeliveriesActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(153, 153, 153));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log Out");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnPendingDriver.setBackground(new java.awt.Color(153, 153, 153));
        btnPendingDriver.setForeground(new java.awt.Color(255, 255, 255));
        btnPendingDriver.setText("Pending Driver");
        btnPendingDriver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPendingDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendingDriverActionPerformed(evt);
            }
        });

        btnOutForDelivery.setBackground(new java.awt.Color(153, 153, 153));
        btnOutForDelivery.setForeground(new java.awt.Color(255, 255, 255));
        btnOutForDelivery.setText("Out for Delivery");
        btnOutForDelivery.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOutForDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutForDeliveryActionPerformed(evt);
            }
        });

        btnCompleted.setBackground(new java.awt.Color(153, 153, 153));
        btnCompleted.setForeground(new java.awt.Color(255, 255, 255));
        btnCompleted.setText("Completed");
        btnCompleted.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletedActionPerformed(evt);
            }
        });

        btnViewDrivers.setBackground(new java.awt.Color(153, 153, 153));
        btnViewDrivers.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDrivers.setText("View Drivers");
        btnViewDrivers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDrivers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDriversActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(705, 705, 705)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnViewTrucks, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDeleteTrucks, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddTrucks, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnViewDeliveries, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPendingDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnOutForDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCompleted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewDrivers, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                .addGap(66, 66, 66)
                                .addComponent(btnCompleteDeliveries, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDeliveries)
                    .addComponent(btnPendingDriver)
                    .addComponent(btnOutForDelivery)
                    .addComponent(btnCompleted)
                    .addComponent(btnCompleteDeliveries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewTrucks)
                    .addComponent(btnDeleteTrucks)
                    .addComponent(btnAddTrucks)
                    .addComponent(btnViewDrivers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String url = "jdbc:mysql://localhost:3306/myproject";
    String user = "root";
    String pass = "";
    private void btnViewDeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeliveriesActionPerformed
        DefaultTableModel model = (DefaultTableModel)DeliveriesTable.getModel();
        model.setRowCount(0);
        
        try{
            Connection conn = DriverManager.getConnection(url, user, pass);
            String sql = "SELECT DISTINCT Deliveries.TruckID, Deliveries.PickUpAddress, Deliveries.DropOffAddress, Deliveries.Status, Users.Username\n" +
                         "FROM Deliveries\n" +
                         "INNER JOIN Users ON Users.UserID = Deliveries.UserID\n";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                int TruckID = rs.getInt("TruckID");
                String PickUpAddress = rs.getString("PickUpAddress");
                String DropOffAddress = rs.getString("DropOffAddress");
                String Status = rs.getString("Status");
                String Username = rs.getString("Username");
                
                model.addRow(new Object[]{TruckID, PickUpAddress, DropOffAddress, Status, Username});
            }           
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnViewDeliveriesActionPerformed

    public void viewDeliveries(){
        DefaultTableModel model = (DefaultTableModel)DeliveriesTable.getModel();
        model.setRowCount(0);
        
        try{
            Connection conn = DriverManager.getConnection(url, user, pass);
            String sql = "SELECT DISTINCT Deliveries.TruckID, Deliveries.PickUpAddress, Deliveries.DropOffAddress, Deliveries.Status, Users.Username\n" +
                         "FROM Deliveries\n" +
                         "INNER JOIN Users ON Users.UserID = Deliveries.UserID\n";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                int TruckID = rs.getInt("TruckID");
                String PickUpAddress = rs.getString("PickUpAddress");
                String DropOffAddress = rs.getString("DropOffAddress");
                String Status = rs.getString("Status");
                String Username = rs.getString("Username");
                
                model.addRow(new Object[]{TruckID, PickUpAddress, DropOffAddress, Status, Username});
            }           
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void viewDeliveries(String Filter){
        DefaultTableModel model = (DefaultTableModel)DeliveriesTable.getModel();
        model.setRowCount(0);
        
        try{
            Connection conn = DriverManager.getConnection(url, user, pass);
            String sql = "SELECT DISTINCT Deliveries.TruckID, Deliveries.PickUpAddress, Deliveries.DropOffAddress, Deliveries.Status, Users.Username\n" +
                         "FROM Deliveries\n" +
                         "INNER JOIN Users ON Users.UserID = Deliveries.UserID\n"
                       + "WHERE Deliveries.Status = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, Filter);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                int TruckID = rs.getInt("TruckID");
                String PickUpAddress = rs.getString("PickUpAddress");
                String DropOffAddress = rs.getString("DropOffAddress");
                String Status = rs.getString("Status");
                String Username = rs.getString("Username");
                
                model.addRow(new Object[]{TruckID, PickUpAddress, DropOffAddress, Status, Username});
            }           
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    private void btnAddTrucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTrucksActionPerformed
        AddTrucks AT = new AddTrucks();
        AT.show();
        dispose();
    }//GEN-LAST:event_btnAddTrucksActionPerformed

    private void btnViewTrucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTrucksActionPerformed
        ViewTrucks VT = new ViewTrucks();
        VT.viewTrucksTable();
        VT.show();
    }//GEN-LAST:event_btnViewTrucksActionPerformed

    private void btnCompleteDeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteDeliveriesActionPerformed
        CompleteDeliveries CD = new CompleteDeliveries();
        CD.show();
    }//GEN-LAST:event_btnCompleteDeliveriesActionPerformed

    private void btnDeleteTrucksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTrucksActionPerformed
        DeleteTrucks DT = new DeleteTrucks();
        ViewTrucks VT = new ViewTrucks();
        VT.viewTrucksTable();
        VT.show();
        DT.show();
    }//GEN-LAST:event_btnDeleteTrucksActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int y = JOptionPane.showConfirmDialog(
                null,
                "Log out?",
                "Confirm",
                JOptionPane.YES_NO_OPTION);
        
        if(y == JOptionPane.YES_OPTION){
            Log_in_Frame LOF = new Log_in_Frame();
            LOF.show();
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPendingDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingDriverActionPerformed
       viewDeliveries("Pending Driver");
    }//GEN-LAST:event_btnPendingDriverActionPerformed

    private void btnOutForDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutForDeliveryActionPerformed
        viewDeliveries("Out for Delivery");
    }//GEN-LAST:event_btnOutForDeliveryActionPerformed

    private void btnCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletedActionPerformed
        viewDeliveries("Completed");
    }//GEN-LAST:event_btnCompletedActionPerformed

    private void btnViewDriversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDriversActionPerformed
        viewDrivers VD = new viewDrivers();
        VD.viewDrivers();
        VD.show();
    }//GEN-LAST:event_btnViewDriversActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DeliveriesTable;
    private javax.swing.JButton btnAddTrucks;
    private javax.swing.JButton btnCompleteDeliveries;
    private javax.swing.JButton btnCompleted;
    private javax.swing.JButton btnDeleteTrucks;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOutForDelivery;
    private javax.swing.JButton btnPendingDriver;
    private javax.swing.JButton btnViewDeliveries;
    private javax.swing.JButton btnViewDrivers;
    private javax.swing.JButton btnViewTrucks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
