package HOME;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class Trucks_Table extends javax.swing.JFrame {

    /**
     * Creates new form Trucks_Table
     */
    public Trucks_Table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Trucks_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        edtTruckID = new javax.swing.JTextField();
        btnConfirmTruck = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Trucks_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Truck ID", "Truck Name", "Truck Size", "Capacity/KG", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Trucks_Table.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Trucks_TableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Trucks_Table);
        if (Trucks_Table.getColumnModel().getColumnCount() > 0) {
            Trucks_Table.getColumnModel().getColumn(0).setResizable(false);
            Trucks_Table.getColumnModel().getColumn(1).setResizable(false);
            Trucks_Table.getColumnModel().getColumn(2).setResizable(false);
            Trucks_Table.getColumnModel().getColumn(3).setResizable(false);
            Trucks_Table.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Pick Truck");

        edtTruckID.setText("Truck ID");
        edtTruckID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTruckIDActionPerformed(evt);
            }
        });

        btnConfirmTruck.setText("Confirm");
        btnConfirmTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmTruckActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtTruckID)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(btnConfirmTruck))
                                .addGap(0, 126, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtTruckID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConfirmTruck)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBack)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        String url = "jdbc:mysql://localhost:3306/mysql";
        String user = "root";
        String pass = "";
        
    public void displayTrucks(){
        DefaultTableModel model = (DefaultTableModel)Trucks_Table.getModel();
        
        model.setRowCount(0);
        String TruckSize = SessionManager.getInstance().getTruckSize();
        
        try{
            Connection conn = DriverManager.getConnection(url, user, pass); 
            String sql = "SELECT TruckID, TruckName, TruckSize, Capacity, Status FROM myproject.Trucks WHERE TruckSize = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, TruckSize);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                String TruckName = rs.getString("TruckName");
                String Size = rs.getString("TruckSize");
                double Capacity = rs.getDouble("Capacity");
                String Status = rs.getString("Status");
                int TruckID = rs.getInt("TruckID");

                
                model.addRow(new Object[]{TruckID, TruckName, Size, Capacity, Status});
            }
        }catch(Exception e){
            e.printStackTrace();
        }   
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        SessionManager.getInstance().resetTruckID();
        BookTruck BT = new BookTruck();
        BT.show();
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnConfirmTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmTruckActionPerformed
        String TruckSize = SessionManager.getInstance().getTruckSize();
        int SelectedTruckID = Integer.parseInt(edtTruckID.getText());
        SessionManager.getInstance().setTruckID(SelectedTruckID);
        
        try{
            Connection conn = DriverManager.getConnection(url, user, pass);
            String checkTruck = "SELECT Status, Capacity, TruckName FROM myproject.Trucks WHERE TruckSize = ? AND TruckID = ?";
            PreparedStatement checkpstmt = conn.prepareStatement(checkTruck);
            checkpstmt.setString(1, TruckSize);
            checkpstmt.setInt(2, SelectedTruckID);
            ResultSet rs = checkpstmt.executeQuery();
            
            if (!rs.next()) {
            JOptionPane.showMessageDialog(null, "Truck not Found");
            return;
            } else {
                double Capacity = rs.getDouble("Capacity");
                String TruckName = rs.getString("TruckName");
                String Status = rs.getString("Status");
                
                SessionManager.getInstance().setCapacity(Capacity);
                SessionManager.getInstance().setTruckName(TruckName);
                SessionManager.getInstance().setTruckStatus(Status);
            }
            
            String TruckStatusFromDB = rs.getString("Status");
            if("In Service".equals(TruckStatusFromDB)){
                JOptionPane.showMessageDialog(null, "Truck In Service");
                return;
            } 

        }catch(Exception e){
            e.printStackTrace();
        }
        
        String TruckName = SessionManager.getInstance().getTruckName();
        double Capacity = SessionManager.getInstance().getCapacity();
        
        LoadObjects LO = new LoadObjects(TruckName, Capacity);
        SessionManager.getInstance().display();
        LO.show();
        dispose();
    }//GEN-LAST:event_btnConfirmTruckActionPerformed

    private void Trucks_TableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Trucks_TableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Trucks_TableAncestorAdded

    private void edtTruckIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTruckIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTruckIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trucks_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trucks_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trucks_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trucks_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trucks_Table().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Trucks_Table;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmTruck;
    private javax.swing.JTextField edtTruckID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
